export const TMDB_URL = "https://api.themoviedb.org/3/";
export const API_KEY = "1a65d41cd57fab7537d17820063e63df";
export const IMAGE_URL = "https://image.tmdb.org/t/p/";
export const BACKDROP_SIZE = "w1280_and_h720_bestv2";
export const POSTER_SIZE = "w185_and_h278_bestv2";
export const MOVIE_CARD_SIZE = "w342"
export const LOGO_SIZE = "w92";
export const PROFILE_SIZE = "w45"
export const DISCOVER_LIST= ["Popular Movies","Now Playing Movies", "Top Rated Movies"]